services:
  backend:
    build:
      context: ./app/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_NAME=${MAIL_NAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cosmeticguardian
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=cosmeticguardian
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: